# Generated by Django 6.0.2 on 2026-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
