# Generated by Django 6.0.2 on 2026-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_add_token_counts_to_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
