# Generated by Django 6.0.2 on 2026-02-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_thread_id_message_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='retrieved_chunks',
        ),
    ]
