# Generated by Django 6.0.2 on 2026-02-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_documentchunk_and_retrieved_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='thread_id',
        ),
    ]
