# Generated by Django 6.0.2 on 2026-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_cleanup_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
