# Generated by Django 6.0.2 on 2026-02-10 14:47

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='documents/')),
                ('authority_level', models.CharField(choices=[('statute', 'Statute'), ('rule', 'Rule'), ('case', 'Case'), ('practice_guide', 'Practice Guide')], max_length=20)),
                ('domain', models.CharField(choices=[('family', 'Family'), ('criminal', 'Criminal'), ('civil', 'Civil'), ('property', 'Property'), ('probate', 'Probate'), ('business', 'Business'), ('employment', 'Employment'), ('immigration', 'Immigration'), ('other', 'Other')], max_length=20)),
                ('jurisdiction', models.CharField(default='TX', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('source_file', models.CharField(max_length=500)),
                ('page', models.CharField(blank=True, default='', max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('authority_level', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('jurisdiction', models.CharField(default='TX', max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['jurisdiction', 'domain'], name='documents_d_jurisdi_286a13_idx'), models.Index(fields=['authority_level'], name='documents_d_authori_5ead72_idx'), models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx')],
            },
        ),
    ]
