# Generated by Django 6.0.2 on 2026-02-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('md5_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('modified_time', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_file', to='documents.document')),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
    ]
