# Generated by Django 6.0.2 on 2026-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_drivefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='openai_file_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
