# Generated by Django 6.0.2 on 2026-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_openai_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
    ]
