# Generated by Django 6.0.2 on 2026-02-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_documentchunk_and_retrieved_chunks'),
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_jurisdi_286a13_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_authori_5ead72_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_documen_8ea6ce_idx',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
